rename project to neomod
TODOs:
- new logo
- server-side integration:
 - handle old neosu versions while neosu.net is still active (mirror endpoints for a while)
 - handle scores starting with "neomod-" for client
 - move neosu-submit-map.php to neomod-submit-map.php
 - handle neomod-mods score mime parts
- client-side migration:
 - move old neosu_maps.db and neosu_scores.db to neomod_ prefixed versions
 - handle updating from neosu.exe to neomod.exe
 - not really much else i think?

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,7 +3,7 @@ AM_MAKEFLAGS := $(MAKEFLAGS)
 PATH := $(DEPS_PREFIX):$(shell echo $$PATH)
 export PATH
 
-bin_PROGRAMS = neosu
+bin_PROGRAMS = neomod
 
 # generated by ./autogen.sh (includes conditional source blocks)
 include $(top_srcdir)/src/Makefile.sources
@@ -137,7 +137,7 @@ $(DEPS_CACHE)/linux_dxc_2025_07_14.x86_64.tar.gz:
 
 # TEMPTEMP: beatmap pack for WASM demo (pre-extracted)
 # this is going through the "osu! stable raw load" path for database loading,
-# for some reason we still only have raw loading of .osz files for neosu_maps (TODO)
+# for some reason we still only have raw loading of .osz files for neomod_maps (TODO)
 WASM_BEATMAP_PACK_URL := "https://packs.ppy.sh/S1757%20-%20osu%21%20Beatmap%20Pack%20%231757.zip"
 $(DEPS_CACHE)/wasm-beatmap-pack.zip:
 	$(MKDIR_P) $(DEPS_CACHE)
@@ -1276,7 +1276,7 @@ $(DEPS_PREFIX)/libacl-$(LIBACL_VERSION).built:
 endif # BUILD_LIBARCHIVE
 
 if BUILD_WINPTHREAD_NOVERSION
-# strip version.o from winpthread to avoid it overwriting neosu_resource contents
+# strip version.o from winpthread to avoid it overwriting neomod_resource contents
 $(DEPS_PREFIX)/winpthread-noversion.built: | $(DEPS_PREFIX)
 	$(MKDIR_P) $(DEPS_PREFIX)/lib
 	cp "$(WINPTHREAD_ORIG)" $(DEPS_PREFIX)/lib/libwinpthread_noversion.a
@@ -1378,7 +1378,7 @@ $(EMBED_OUTPUT): $(EMBED_SCRIPT) $(EMBED_MANIFESTS) $(EMBED_CACERT_DEPS) $(SDLGP
 
 -include $(EMBED_DEPFILE)
 
-neosu_SOURCES += $(EMBED_OUTPUT)
+neomod_SOURCES += $(EMBED_OUTPUT)
 CLEANFILES += $(EMBED_OUTPUT) $(builddir)/gen/binary_embed.h $(EMBED_DEPFILE) $(EMBED_CONFIG_STAMP) \
 	$(builddir)/gen/shaders/*.shdpk $(builddir)/gen/shaders/*.spv $(builddir)/gen/shaders/*.dxil \
 	$(builddir)/gen/shaders/sdlgpu_shaders.manifest $(builddir)/gen/shaders/.stamp
@@ -1442,7 +1442,7 @@ $(PCH_OUTPUT): $(PCH_SOURCE) $(BUILT_SOURCES)
 	@rm -f $(PCH_OUTPUT) # remove possibly existing-but-outdated pch to avoid recursively including it (sanity)
 	@$(MKDIR_P) $(dir $@)
 	$(CXX) -x c++-header -MMD -MF $(PCH_DEPS) $(PCH_BUILD_FLAGS) \
-		$(CPPFLAGS) $(neosu_CPPFLAGS) $(neosu_CXXFLAGS) $(CXXFLAGS) \
+		$(CPPFLAGS) $(neomod_CPPFLAGS) $(neomod_CXXFLAGS) $(CXXFLAGS) \
 		-o $@ $(PCH_SOURCE)
 
 -include $(PCH_DEPS)
@@ -1458,22 +1458,22 @@ endif # BUILD_PCH
 
 # making sure deps are built before main compile
 # EMBED_OUTPUT is order-only (after |): must exist before compilation, but updating it doesn't rebuild all objects
-# (only binary_embed.o through neosu_SOURCES dep)
-$(neosu_OBJECTS): $(BUILT_SOURCES) $(PCH_OUTPUT) | $(EMBED_OUTPUT)
+# (only binary_embed.o through neomod_SOURCES dep)
+$(neomod_OBJECTS): $(BUILT_SOURCES) $(PCH_OUTPUT) | $(EMBED_OUTPUT)
 
 # add all paths with sources as an include ("-I") flag
-NEOSU_INCLUDE_FLAGS := $(shell find $(srcdir)/src -not -path '*/.*' -type d -printf "-I%p ")
+NEOMOD_INCLUDE_FLAGS := $(shell find $(srcdir)/src -not -path '*/.*' -type d -printf "-I%p ")
 
-neosu_CPPFLAGS := $(NEOSU_CPPFLAGS)
+neomod_CPPFLAGS := $(NEOMOD_CPPFLAGS)
 
-neosu_CXXFLAGS := \
+neomod_CXXFLAGS := \
 	-I$(builddir) \
 	-I$(builddir)/src \
 	-I$(builddir)/gen \
 	$(PCH_FLAGS) \
 	-I$(DEPS_PREFIX)/include \
 	$(BUNDLED_INCLUDES) \
-	$(NEOSU_INCLUDE_FLAGS) \
+	$(NEOMOD_INCLUDE_FLAGS) \
 	$(CURL_CFLAGS) \
 	$(SDL3_CFLAGS) \
 	$(AUDIO_CFLAGS) \
@@ -1498,13 +1498,13 @@ neosu_CXXFLAGS := \
 	$(SIMDUTF_CFLAGS) \
 	$(CTRE_CFLAGS) \
 	$(DISCORDSDK_CFLAGS) \
-	$(NEOSU_CXXFLAGS) \
+	$(NEOMOD_CXXFLAGS) \
 	$(CXXFLAGS_EXTRA)
 
 # Wl,--start-group with no --end-group is a stupid hack. it's required to make the linker resolve all the symbols on windows, for some reason (i don't know why)
 # harmless on other platforms, i think
 # WASM_PRELOAD_FLAGS and NATIVE_LDFLAGS come from configure (empty when not applicable)
-neosu_LDFLAGS := \
+neomod_LDFLAGS := \
 	$(WASM_PRELOAD_FLAGS) \
 	$(NATIVE_LDFLAGS) \
 	$(MIMALLOC_OBJ) \
@@ -1523,22 +1523,22 @@ neosu_LDFLAGS := \
 	$(LZMA_LIBS) \
 	$(NSYNC_LIBS) \
 	$(SIMDUTF_LIBS) \
-	$(NEOSU_LDFLAGS) \
+	$(NEOMOD_LDFLAGS) \
 	$(EXTRA_WIN_LDFLAGS) \
 	$(LDFLAGS_EXTRA)
 
 # extracted maps dependency (only applicable for wasm but avoids += (slow))
-EXTRA_neosu_DEPENDENCIES := $(EXTRACTED_MAPS_DEP) $(WASM_POLYFILL_DEP)
+EXTRA_neomod_DEPENDENCIES := $(EXTRACTED_MAPS_DEP) $(WASM_POLYFILL_DEP)
 
 if WIN_PLATFORM
 # mimalloc new/delete override for windows
-neosu_SOURCES += $(MIMALLOC_OVERRIDE_DEP)
+neomod_SOURCES += $(MIMALLOC_OVERRIDE_DEP)
 
 # windows icon/resource things
-neosu_resource.o: $(srcdir)/$(ASSETS_DIR)/resource.rc $(srcdir)/$(ASSETS_DIR)/neosu.manifest $(srcdir)/$(ASSETS_DIR)/icon.ico
-	$(WINDRES) -I $(srcdir)/$(ASSETS_DIR) -i $(srcdir)/$(ASSETS_DIR)/resource.rc -o neosu_resource.o
+neomod_resource.o: $(srcdir)/$(ASSETS_DIR)/resource.rc $(srcdir)/$(ASSETS_DIR)/neomod.manifest $(srcdir)/$(ASSETS_DIR)/icon.ico
+	$(WINDRES) -I $(srcdir)/$(ASSETS_DIR) -i $(srcdir)/$(ASSETS_DIR)/resource.rc -o neomod_resource.o
 
-neosu_LDADD = neosu_resource.o $(WINPTHREAD_LDFLAGS)
+neomod_LDADD = neomod_resource.o $(WINPTHREAD_LDFLAGS)
 endif
 
 bear-check-version:
@@ -1585,13 +1585,13 @@ bear.cfg: bear-check-version
 #	  echo '    ignore: false'; \
 #	  echo '    as: $(if $(findstring yes,$(CLANG)),clang,gcc)' ; } > bear.cfg; fi
 
-# need to manually make sure BUILT_SOURCES (dependencies) are fully built before building the main neosu objects, due to weird
+# need to manually make sure BUILT_SOURCES (dependencies) are fully built before building the main neomod objects, due to weird
 # interactions with sub-makes and parallel jobs
 # also run an extra step to exclude PCH flags
 # this is so that you avoid missing includes when it's already in the PCH and clangd then thinks it's already included
 compile_commands.json: bear.cfg mostlyclean-compile
 	$(BEAR) --config bear.cfg --append -- $(MAKE_PFX) $(MAKE) $(AM_MAKEFLAGS) $(BUILT_SOURCES) && \
-	$(BEAR) --config bear.cfg --append -- $(MAKE_PFX) $(MAKE) $(AM_MAKEFLAGS) $(neosu_OBJECTS) $(neosu_DEPENDENCIES) $(EXTRA_neosu_DEPENDENCIES) && \
+	$(BEAR) --config bear.cfg --append -- $(MAKE_PFX) $(MAKE) $(AM_MAKEFLAGS) $(neomod_OBJECTS) $(neomod_DEPENDENCIES) $(EXTRA_neomod_DEPENDENCIES) && \
 	$(SED) -i '/"-include",/{N;/"\.\/pch\.h",/d;}' $@
 
 $(abs_top_srcdir)/.clangd: compile_commands.json
@@ -1631,7 +1631,7 @@ INSTALL_RPATH_STAMP =
 
 if WASM_PLATFORM
 # WASM: assets are preloaded into the .wasm via --preload-file, just install the web files
-WASM_INSTALL_FILES = neosu.js neosu.wasm
+WASM_INSTALL_FILES = neomod.js neomod.wasm
 
 $(DESTDIR)$(bindir)/%: % | install-dirs
 	$(INSTALL) -Dm 644 $< $@
@@ -1640,9 +1640,9 @@ install-dirs:
 	$(INSTALL) -dm 755 "$(DESTDIR)$(bindir)"
 
 install-libs: install-dirs $(addprefix $(DESTDIR)$(bindir)/,$(WASM_INSTALL_FILES))
-	@test -f neosu.worker.js && $(INSTALL) -Cm 644 neosu.worker.js "$(DESTDIR)$(bindir)/" || true
-	@test -f neosu.data && $(INSTALL) -Cm 644 neosu.data "$(DESTDIR)$(bindir)/" || true
-	@test -f neosu.wasm.map && $(INSTALL) -Cm 644 neosu.wasm.map "$(DESTDIR)$(bindir)/" || true
+	@test -f neomod.worker.js && $(INSTALL) -Cm 644 neomod.worker.js "$(DESTDIR)$(bindir)/" || true
+	@test -f neomod.data && $(INSTALL) -Cm 644 neomod.data "$(DESTDIR)$(bindir)/" || true
+	@test -f neomod.wasm.map && $(INSTALL) -Cm 644 neomod.wasm.map "$(DESTDIR)$(bindir)/" || true
 
 else # !WASM_PLATFORM
 
@@ -1762,10 +1762,10 @@ stamp-install-wine-shortcuts: | install-dirs
 	@cd "$(DESTDIR)$(bindir)" && \
 	for backend in $(AUDBACKENDLIST); do \
 		echo 'Set WshShell = CreateObject("WScript.Shell")' > temp.vbs && \
-		echo "Set Shortcut = WshShell.CreateShortcut(\"neosu-$$backend.lnk\")" >> temp.vbs && \
+		echo "Set Shortcut = WshShell.CreateShortcut(\"neomod-$$backend.lnk\")" >> temp.vbs && \
 		echo 'Shortcut.TargetPath = "C:\Windows\System32\cmd.exe"' >> temp.vbs && \
 		echo "Shortcut.Arguments = \"/c start \"\"\"\" \"\".\\$(PROGRAMS)\"\" -sound $$backend\"" >> temp.vbs && \
-		echo "Shortcut.Description = \"neosu with the $$backend audio backend\"" >> temp.vbs && \
+		echo "Shortcut.Description = \"neomod with the $$backend audio backend\"" >> temp.vbs && \
 		echo 'Shortcut.WindowStyle = 7' >> temp.vbs && \
 		echo 'Shortcut.Save' >> temp.vbs && \
 		WINEPREFIX=$(TEMP_WINEPFX) DISPLAY= WAYLAND_DISPLAY= WINEDLLOVERRIDES="mscoree=;mshtml=;winex11.drv=;winewayland.drv=" WINEDEBUG=-all \
@@ -1803,7 +1803,7 @@ if LINUX_PLATFORM
 	$(LN_S) -f $(PROGRAMS) McOsu
 else
 if WIN_PLATFORM
-	@cp -P neosu.pdb "$(DESTDIR)$(bindir)" &>/dev/null || true # don't fail install if we had no pdb
+	@cp -P neomod.pdb "$(DESTDIR)$(bindir)" &>/dev/null || true # don't fail install if we had no pdb
 endif # WIN_PLATFORM
 endif # LINUX_PLATFORM
 
